using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using NJsonSchema;
using NJsonSchema.CodeGeneration.CSharp;

namespace Viu.Emporix.MixinSync;

/// <summary>
/// Turns mixin schemas into C# types, serializer contexts and a registry.
/// </summary>
/// <remarks>
/// Uses NJsonSchema as a library rather than shelling out to the nswag CLI, so
/// the namespace can be set per mixin and the consumer needs no tool manifest.
/// </remarks>
public static partial class Generator
{
    private const string Banner = "// AUTO-GENERATED by Viu.Emporix.MixinSync — do not edit.";

    /// <summary>Generates every file for a set of mixins.</summary>
    /// <param name="mixins">The mixins, as pulled.</param>
    /// <param name="rootNamespace">The namespace the generated code goes under.</param>
    /// <returns>File name to content, including <c>Registry.g.cs</c>.</returns>
    /// <exception cref="InvalidOperationException">
    /// Two attributes of one mixin normalise to the same C# name.
    /// </exception>
    public static IReadOnlyDictionary<string, string> Generate(
        IEnumerable<RawMixin> mixins,
        string rootNamespace)
    {
        ArgumentNullException.ThrowIfNull(mixins);
        ArgumentException.ThrowIfNullOrWhiteSpace(rootNamespace);

        Dictionary<string, string> files = new(StringComparer.Ordinal);
        List<string> registryEntries = [];

        // A schema assigned to several entity types arrives several times. The
        // generated type is identical, so emit it once and let the registry
        // carry one descriptor per entity.
        foreach (IGrouping<string, RawMixin> group in mixins.GroupBy(m => m.Key, StringComparer.Ordinal))
        {
            RawMixin mixin = group.First();
            string identifier = Identifier(mixin.Key);
            string mixinNamespace = $"{rootNamespace}.{identifier}";

            (string code, string typeName) = Emit(mixin, identifier, mixinNamespace);
            IReadOnlyDictionary<string, string> attributes = AttributeTable(code, mixin.Key);

            files[$"{identifier}.g.cs"] = code;

            foreach (RawMixin perEntity in group)
            {
                registryEntries.Add(RegistryEntry(perEntity, typeName, identifier, mixinNamespace, attributes));
            }
        }

        files["Registry.g.cs"] = Registry(rootNamespace, registryEntries);

        return files;
    }

    // Returns the code and the type name NJsonSchema actually emitted, which is
    // not always the one it was asked for — it renormalises the name, and
    // everything downstream has to use what came back.
    private static (string Code, string TypeName) Emit(
        RawMixin mixin,
        string identifier,
        string mixinNamespace)
    {
        string requested = $"{identifier}MixinV{mixin.Version.ToString(CultureInfo.InvariantCulture)}";

        JsonSchema schema = JsonSchema.FromJsonAsync(mixin.Schema).GetAwaiter().GetResult();

        string types = new CSharpGenerator(schema, new CSharpGeneratorSettings
        {
            Namespace = mixinNamespace,
            ClassStyle = CSharpClassStyle.Poco,
            JsonLibrary = CSharpJsonLibrary.SystemTextJson,
            GenerateDataAnnotations = false,
            GenerateNullableReferenceTypes = true,
            GenerateOptionalPropertiesAsNullable = true,
        }).GenerateFile(requested);

        string emitted = RootTypePattern().Match(types) is { Success: true } match
            ? match.Groups["name"].Value
            : requested;

        // One context per mixin, without exception: Emporix reuses attribute
        // names across schemas, and a shared context collides on same-named
        // nested types with SYSLIB1031 — an error under warnings-as-errors.
        // WhenWritingNull because a schema with additionalProperties:false has
        // no use for an explicit null.
        string context = $$"""

            namespace {{mixinNamespace}}
            {
                [System.Text.Json.Serialization.JsonSourceGenerationOptions(
                    DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
                [System.Text.Json.Serialization.JsonSerializable(typeof({{emitted}}))]
                public sealed partial class {{identifier}}Context
                    : System.Text.Json.Serialization.JsonSerializerContext;
            }

            """;

        return ($"{Banner}{Environment.NewLine}{types}{context}", emitted);
    }

    private static string RegistryEntry(
        RawMixin mixin,
        string typeName,
        string identifier,
        string mixinNamespace,
        IReadOnlyDictionary<string, string> attributes)
    {
        // A mixin on several entities needs one member per entity, and PRODUCT
        // is left unsuffixed because it is by far the common case.
        string member = mixin.Entity is "PRODUCT"
            ? identifier
            : $"{identifier}On{EntityMember(mixin.Entity)}";

        string table = string.Join(
            ", ",
            attributes.Select(pair => $"[\"{pair.Key}\"] = \"{pair.Value}\""));

        return $$"""
                /// <summary>The «{{mixin.Key}}» mixin on {{mixin.Entity}}, schema version {{mixin.Version}}.</summary>
                public static readonly Viu.Emporix.Mixins.MixinDescriptor<{{mixinNamespace}}.{{typeName}}> {{member}} = new()
                {
                    Key = "{{mixin.Key}}",
                    Entity = "{{mixin.Entity}}",
                    Url = "{{mixin.Url}}",
                    Version = {{mixin.Version.ToString(CultureInfo.InvariantCulture)}},
                    TypeInfo = {{mixinNamespace}}.{{identifier}}Context.Default.{{typeName}},
                    Attributes = new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal) { {{table}} },
                };
        """;
    }

    private static string Registry(string rootNamespace, IEnumerable<string> entries)
        => $$"""
            {{Banner}}
            namespace {{rootNamespace}}
            {
                /// <summary>This tenant's mixins.</summary>
                public static class Mixins
                {
            {{string.Join(Environment.NewLine + Environment.NewLine, entries)}}
                }
            }
            """;

    // Parsed out of the emitted code rather than recomputed. The conversion and
    // the emitted result can diverge, and the Node package tripped on exactly
    // that — its comment reads «reference the name it ACTUALLY emitted».
    private static Dictionary<string, string> AttributeTable(string code, string mixinKey)
    {
        Dictionary<string, string> table = new(StringComparer.Ordinal);

        foreach (Match match in PropertyPattern().Matches(code))
        {
            string json = match.Groups["json"].Value;
            string clr = match.Groups["clr"].Value;

            if (table.TryGetValue(clr, out string? first)
                && !string.Equals(first, json, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    $"The mixin \"{mixinKey}\" has attributes \"{first}\" and \"{json}\", which both become the C# name {clr}. The generated code would not compile. Rename one of them in the schema.");
            }

            table[clr] = json;
        }

        return table;
    }

    // Entity types arrive as SCREAMING_SNAKE from the SchemaType enum, so they
    // need the opposite treatment to a schema key: lower-case the run and
    // capitalise each segment. Identifier would leave CUSTOMER_ADDRESS as
    // CUSTOMERADDRESS, because it preserves interior capitals on purpose —
    // deliveryOptions has to stay DeliveryOptions.
    private static string EntityMember(string entity)
        => string.Concat(entity
            .Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(segment => string.Concat(
                char.ToUpperInvariant(segment[0]),
                segment[1..].ToLowerInvariant())));

    /// Emporix schema ids can be object ids, which cannot start a C# name.
    private static string Identifier(string value)
    {
        StringBuilder builder = new();
        bool upper = true;

        foreach (char character in value)
        {
            if (!char.IsLetterOrDigit(character))
            {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(character) : character);
            upper = false;
        }

        string identifier = builder.ToString();

        return identifier.Length == 0 || !char.IsLetter(identifier[0])
            ? $"Mixin{identifier}"
            : identifier;
    }

    [GeneratedRegex(
        """JsonPropertyName\("(?<json>[^"]+)"\)\]\s*public\s+[^\s]+\s+(?<clr>\w+)\s*\{""",
        RegexOptions.Singleline)]
    private static partial Regex PropertyPattern();

    [GeneratedRegex(
        """public\s+partial\s+class\s+(?<name>\w+)""",
        RegexOptions.None)]
    private static partial Regex RootTypePattern();
}
