openapi: 3.0.0
info:
  title: Configuration Service
  version: ''
  contact:
    email: documentation@emporix.com
  description: |-
    General store for tenant-specific information.
servers:
  - url: 'https://api.emporix.io'
tags:
  - name: Tenant configurations
    description: Manage Tenant Configurations
  - name: Client configurations
    description: Manage Client Configurations
  - name: Global configurations
    description: Read Global Configurations
paths:
  '/configuration/{tenant}/global-configurations':
    get:
      summary: Retrieving global configurations
      tags:
        - Global configurations
      operationId: GET-global-configuration-list-config
      description: |-
        Retrieves a list of global configurations.
  '/configuration/{tenant}/configurations':
    get:
      summary: Retrieving configurations
      tags:
        - Tenant configurations
      operationId: GET-configuration-list-config
      security:
        - OAuth2:
            - configuration.configuration_view
      description: |-
        Retrieves a list of configurations.
    post:
      summary: Creating configurations
      operationId: POST-configuration-create-config
      security:
        - OAuth2:
            - configuration.configuration_manage
      description: |-
        Creates new configurations.
      tags:
        - Tenant configurations
  '/configuration/{tenant}/configurations/{propertyKey}':
    get:
      summary: Retrieving a configuration
      tags:
        - Tenant configurations
      operationId: GET-configuration-retrieve-config
      security:
        - OAuth2:
            - configuration.configuration_view
      description: |-
        Retrieves a specified configuration.
    put:
      summary: Updating a configuration
      operationId: PUT-configuration-update-config
      security:
        - OAuth2:
            - configuration.configuration_manage
      description: |-
        Updates a specified configuration.
      tags:
        - Tenant configurations
    delete:
      summary: Deleting a configuration
      operationId: DELETE-configuration-remove-config
      security:
        - OAuth2:
            - configuration.configuration_manage
      description: |-
        Deletes a specified configuration.
      tags:
        - Tenant configurations
  '/configuration/{tenant}/clients':
    get:
      summary: Retrieving clients
      tags:
        - Client configurations
      operationId: GET-configuration-list-clients
      security:
        - OAuth2:
            - configuration.configuration_view
      description: |-
        Retrieves a list of clients for a specified tenant.
  '/configuration/{tenant}/clients/{client}/configurations':
    get:
      summary: Retrieving client configurations
      tags:
        - Client configurations
      operationId: GET-configuration-list-client-config
      security:
        - OAuth2:
            - configuration.configuration_view
      description: |-
        Retrieves a list of configurations for a specified client.
    post:
      summary: Creating client configurations
      operationId: POST-configuration-create-client-config
      security:
        - OAuth2:
            - configuration.configuration_manage
      description: |-
        Creates a new client configuration.
      tags:
        - Client configurations
  '/configuration/{tenant}/clients/{client}/configurations/{propertyKey}':
    get:
      summary: Retrieving a client configuration
      tags:
        - Client configurations
      operationId: GET-configuration-retrieve-client-config

      security:
        - OAuth2:
            - configuration.configuration_view
      description: |-
        Retrieves a specified client configuration.
    put:
      summary: Updating a client configuration
      operationId: PUT-configuration-update-client-config
      security:
        - OAuth2:
            - configuration.configuration_manage
      tags:
        - Client configurations
      description: |-
        Updates a specified client configuration.
    delete:
      summary: Deleting a client configuration
      operationId: DELETE-configuration-remove-client-config
      security:
        - OAuth2:
            - configuration.configuration_manage
      tags:
        - Client configurations
      description: |-
        Deletes a specified client configuration.
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          refreshUrl: ''
          scopes:
            configuration.configuration_view: ''
            configuration.configuration_manage: ''
          tokenUrl: 'https://api.emporix.io/oauth/token'
security:
  - OAuth2: []