openapi: 3.0.0
info:
  contact:
    name: Emporix
    url: https://emporix.com
    email: documentation@emporix.com
  title: Fee Service
  version: v1
servers:
  - url: 'https://api.emporix.io'
paths:
  '/fee/{tenant}/fees':
    get:
      tags:
        - Fee management
      summary: Retrieving fees
      description: |
        Retrieves all fees for a tenant.
      operationId: GET-fee-list-all-fees
    post:
      tags:
        - Fee management
      summary: Creating a fee
      description: |
        Creates a new fee within a specified tenant. Fees can be applied to various entities, such as products or payment methods, to manage pricing structures effectively.
      security:
        - OAuth2: 
            - fee.fee_create
      operationId: POST-fee-create-fee
  '/fee/{tenant}/fees/{id}':
    get:
      description: |
        Retrieve the details of a fee by id.
      tags:
        - Fee management
      summary: Retrieving a fee by id
      operationId: GET-fee-retrieve-fee
    put:
      description: |
        Update the details of an existing fee.
      security:
        - OAuth2: 
            - fee.fee_update
      tags:
        - Fee management
      summary: Updating a fee
      operationId: PUT-fee-update-fee
    delete:
      description: |
        Deletes a fee by given id.
      security:
        - OAuth2: 
            - fee.fee_delete
      tags:
        - Fee management
      summary: Deleting a fee
      operationId: DELETE-fee-remove-fee
  '/fee/{tenant}/itemFees':
    get:
      description: |
        Retrieve all itemFees.
      tags:
        - Item fee management
      summary: Retrieve all itemFees
      operationId: GET-fee-list-item-fees
    post:
      description: |
        Creates a new itemFee. This endpoint allows you to assign one or more predefined fees to a specific item within a tenant. By associating fees with items, you can manage charges such as packaging, handling, or other service fees directly at the item level.
      security:
        - OAuth2: 
            - fee.item_create
      tags:
        - Item fee management
      summary: Creating an itemFee
      operationId: POST-fee-create-item-fee
  '/fee/{tenant}/itemFees/{itemYRN}/fees':
    get:
      description: |
        Retrieves all item fees for specified itemYRN.
      tags:
        - Item fee management
      summary: Retrieving all item fees
      operationId: GET-fee-list-item-fees-itemYRN
    put:
      description: |
        Adds a list of feeIds to the itemYRN.
      security:
        - OAuth2: 
            - fee.item_update
      tags:
        - Item fee management
      summary: Adding a list of fees to an item
      operationId: PUT-fee-add-item-fees-itemYRN
    delete:
      description: |
        Deletes item fee with the specified itemYRN.
      security:
        - OAuth2: 
            - fee.item_delete
      tags:
        - Item fee management
      summary: Deleting an item fee with itemYRN
      operationId: DELETE-fee-remove-item-fee-with-itemYRN
  '/fee/{tenant}/itemFees/{itemYRN}/fees/{feeId}':
    delete:
      description: |
        Deletes a fee for the specified itemYRN and optionally deletes item fee if does not contain any more fee ids.
      security:
        - OAuth2: 
            - fee.item_delete
      tags:
        - Item fee management
      summary: Deleting a fee from the itemYRN
      operationId: DELETE-fee-remove-item-fee-from-itemYRN
  '/fee/{tenant}/productFees/{productId}/fees':
    get:
      description: |
        Retrieve all fees with given productId.
      tags:
        - Product fees management
      summary: Retrieving all fees with given productId
      operationId: GET-fee-list-product-fees
    put:
      description: |
        Adds a list of feeIds to the itemYRN.
      security:
        - OAuth2: 
            - fee.item_update
      tags:
        - Product fees management
      summary: Adding a list of fees to a product
      operationId: PUT-fee-add-product-fees
    delete:
      description: |
        Deletes item fee with specified productId in the itemYRN.
        ***

        ### Additional scopes information
        Use one or both of the following scopes to authorize the request:
          * `fee.fee_delete` 
          * `fee.item_delete`
      security:
        - OAuth2: 
            - fee.fee_delete
            - fee.item_delete
      tags:
        - Product fees management
      summary: Deleting all fees of an itemYRN
      operationId: DELETE-fee-remove-all-product-fees
  '/fee/{tenant}/productFees/{productId}/fees/{feeId}':
    delete:
      description: |
        Deletes a fee for the specified productId and optionally deletes item fee if does not contain any more fee ids.
        ***

        ### Additional scopes information
        Use one or both of the following scopes to authorize the request:
          * `fee.fee_delete` 
          * `fee.item_delete`
      security:
        - OAuth2: 
            - fee.fee_delete
            - fee.item_delete
      tags:
        - Product fees management
      summary: Deleting a fee from the itemYRN
      operationId: DELETE-fee-remove-product-fee
  '/fee/{tenant}/itemFees/searchByProductId':
    post:
      description: |
        Search itemFees by product ID.
      tags:
        - Item fee search
      summary: Searching itemFees by product ID
      operationId: POST-fee-search-item-fee-by-ProductId
  '/fee/{tenant}/itemFees/searchByProductIds':
    post:
      description: |
        Search itemFees by multiple product IDs.
      tags:
        - Item fee search
      summary: Searching itemFees by product IDs
      operationId: POST-fee-search-multiple-item-fees-by-productIds
  '/fee/{tenant}/itemFees/search':
    post:
      description: |
        Checks if the itemYrns in the request have a fee applied to. Responds with the itemYRN and the corresponding fees.
      tags:
        - Item fee search
      summary: Checking if a fee has been applied
      operationId: POST-fee-check-item-fee
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.emporix.io/oauth/token'
          scopes:
            fee.fee_create: Needed to create a fee.
            fee.fee_update: Needed to update a fee.
            fee.fee_delete: Needed to delete a fee.
            fee.item_create: Needed to create an item fee.
            fee.item_update: Needed to update an item fee.
            fee.item_delete: Needed to delete an item fee.
tags:
  - name: Fee management
  - name: Item fee management
  - name: Product fees management
  - name: Item fee search
security:
  - OAuth2: []