openapi: 3.0.0
info:
  title: Payment-Gateway Service
  version: ''
  contact:
    email: documentation@emporix.com
  description: |-
    The Emporix API Payment-Gateway Service allows you to manage your payment methods.
tags:
  - name: Payment
  - name: Payment mode
  - name: Payment - frontend
  - name: Payment mode - frontend
  - name: Transaction
servers:
  - url: 'https://api.emporix.io'
paths:
  '/payment-gateway/{tenant}/paymentmodes/config':
    post:
      summary: Creating a single payment mode entity
      description: |
        Creates a new payment mode for a given tenant. Currently the service supports the following payment methods:

        * Payment methods supported by Spreedly: https://docs.spreedly.com/reference/supported-gateways/
        * Saferpay: https://docs.saferpay.com/home/interfaces/payment-api
        * Unzer Invoice: https://docs.unzer.com/payment-methods/unzer-invoice-upl/
      operationId: POST-payment-gateway-create-payment-mode
      security:
        - OAuth2:
            - payment-gateway.paymentmodes_manage
      tags:
        - Payment mode
    get:
      summary: Retrieving a list of payment modes
      operationId: GET-payment-gateway-list-payment-modes
      tags:
        - Payment mode
      description: |
        Retrieves a list of configured payment modes for a given tenant. 
      security:
        - OAuth2:
            - payment-gateway.paymentmodes_read
  '/payment-gateway/{tenant}/paymentmodes/config/{id}':
    get:
      summary: Retrieving a single payment mode
      tags:
        - Payment mode
      operationId: GET-payment-gateway-retrieve-payment-mode
      description: |
        Retrieves a single payment mode configuration for a given tenant based on a payment mode identifier. 
      security:
        - OAuth2:
            - payment-gateway.paymentmodes_read
    put:
      summary: Updating a single payment mode
      operationId: PUT-payment-gateway-update-payment-mode
      description: |
        Updates a single payment mode for a given tenant based on a unique mode identifier. 
      security:
        - OAuth2:
            - payment-gateway.paymentmodes_manage
      tags:
        - Payment mode
    delete:
      summary: Deleting a single payment mode
      operationId: DELETE-payment-gateway-remove-payment-mode
      description: |
        Deletes a single payment mode for a given tenant based on a unique mode identifier. 
      security:
        - OAuth2:
            - payment-gateway.paymentmodes_manage
      tags:
        - Payment mode
  '/payment-gateway/{tenant}/paymentmodes/frontend':
    get:
      summary: Retrieving all the payment modes
      tags:
        - Payment mode - frontend
      operationId: GET-payment-gateway-list-payment-modes-frontend
      description: |
        Retrieves a list of configured payment modes for a given tenant with publicly available properties (excluding all secrets, signatures etc). 
        The endpoint should be used by a frontend application to fetch all the possible payment methods configured for a particular tenant. 
        No scope is required.
  '/payment-gateway/{tenant}/paymentmodes/frontend/{id}':
    get:
      summary: Retrieving a single payment mode
      tags:
        - Payment mode - frontend
      operationId: GET-payment-gateway-retrieve-payment-mode-frontend
      description: |
        Retrieves a single payment mode for a given tenant with publicly available properties (excluding all secrets, signatures etc). 
        The endpoint should be used by a frontend application to fetch a payment method configuration for a particular tenant. 
        No scope is required.
  '/payment-gateway/{tenant}/payment/authorize':
    post:
      summary: Authorizing a payment
      operationId: POST-payment-gateway-authorize-payment
      tags:
        - Payment
      description: |
        Authorizes a given payment. 
      security:
        - OAuth2:
            - payment-gateway.authorize_manage
  '/payment-gateway/{tenant}/payment/{transactionId}/capture':
    post:
      summary: Capturing a payment
      operationId: POST-payment-gateway-capture-payment
      tags:
        - Payment
      description: |
        Creates a flow to capture a given payment transaction. The capture operation requires transactionId, thus it can be invoked only if the payment had been previously authorized. 
      security:
        - OAuth2:
            - payment-gateway.capture_manage
  '/payment-gateway/{tenant}/payment/{transactionId}/refund':
    post:
      summary: Refunding a payment
      operationId: POST-payment-gateway-refund-payment
      tags:
        - Payment
      description: |
        Creates a flow to return a given payment. The refund operation requires transactionId, thus it can be invoked only if the payment has been authorized and captured previously. 
      security:
        - OAuth2:
            - payment-gateway.refund_manage
  '/payment-gateway/{tenant}/payment/{transactionId}/cancel':
    post:
      summary: Cancelling a payment
      operationId: POST-payment-gateway-cancel-payment
      tags:
        - Payment
      description: |
        Creates a flow to cancel a given payment transaction. The cancel operation requires transactionId, thus it can be invoked only if the payment has been authorized previously. 

      security:
        - OAuth2:
            - payment-gateway.cancel_manage
  '/payment-gateway/{tenant}/payment/frontend/initialize':
    post:
      summary: Initializing a payment
      operationId: POST-payment-gateway-initialize-payment-frontend
      tags:
        - Payment - frontend
      description: |
        Initializes a payment by accepting a request sent from the frontend.
        No scope is required.
  '/payment-gateway/{tenant}/payment/frontend/authorize':
    post:
      summary: Authorizing a payment
      operationId: POST-payment-gateway-authorize-payment-frontend
      tags:
        - Payment - frontend
      description: |
        Authorize a payment by accepting a request sent from the frontend.
        No scope is required.
  '/payment-gateway/{tenant}/transactions':
    get:
      summary: Retrieving many transactions
      tags:
        - Transaction
      operationId: GET-payment-gateway-list-transactions
      description: |
        Retrieves many payment transactions. A particular transaction contains all transactions' events attached as an entries of the response body.  
      security:
        - OAuth2:
            - payment-gateway.paymenttransactions_read
  '/payment-gateway/{tenant}/transactions/{transactionId}':
    get:
      summary: Retrieving a single transaction
      tags:
        - Transaction
      operationId: GET-payment-gateway-retrieve-transaction-by-transactionId
      security:
        - OAuth2:
            - payment-gateway.paymenttransactions_read
      description: |
        Retrieves a single payment transaction. The transaction contains all the transaction's events attached as an entries of the response body.  
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.emporix.io/oauth/token'
          scopes:
            payment-gateway.paymentmodes_read: Needed for reading payment modes by a tenant employee.
            payment-gateway.paymentmodes_manage: Needed to manage payment modes by a tenant employee.
            payment-gateway.authorize_manage: Needed to perform a payment authorization flow by a tenant employee.
            payment-gateway.capture_manage: Needed to perform a payment capture flow by a tenant employee.
            payment-gateway.refund_manage: Needed to perform a payment refund flow by a tenant employee.
            payment-gateway.cancel_manage: Needed to perform a payment cancel flow by a tenant employee.
            payment-gateway.paymenttransactions_read: Needed to read all transaction details by a tenant employee.
security:
  - OAuth2: []
