openapi: 3.0.0
info:
  title: Pick-Pack Service
  contact:
    email: documentation@emporix.com
  version: ''
  description: |-
    Manage the picking and packing process in-store or in a warehouse.
servers:
  - url: 'https://api.emporix.io'
tags:
  - name: Orders
    description: Manage pick-pack orders
  - name: Order cycles
    description: Manage pick-pack order cycles
  - name: Assignees
    description: Manage pick-pack assignees
  - name: Recalculations
    description: Manage pick-pack recalculations
  - name: Events
    description: Manage pick-pack events
paths:
  '/pick-pack/{tenant}/orders/{orderId}/finish':
    post:
      tags:
        - Orders
      deprecated: true
      description: |
        Finishes a specified order by:
        * Recalculating the current state
        * Changing the order status to `packed`
        * Deleting all assignees
        * Sending an order confirmation email
      security:
        - OAuth2:
            - pickpack.pickpack_manage
      operationId: POST-pick-pack-finish-order
      summary: Finishing an order
  '/pick-pack/{tenant}/orderCycles':
    get:
      tags:
        - Order cycles
      deprecated: true
      description: |
        Extracts all order delivery dates from the current time onwards.
      security:
        - OAuth2:
            - pickpack.pickpack_view
      operationId: GET-pick-pack-retrieve-order-cycles
      summary: Retrieving all order cycles
  '/pick-pack/{tenant}/orders':
    get:
      tags:
        - Orders
      deprecated: true
      description: |
        Retrieves a packlist for the specified delivery date.

        **Note**: If an order has the `packingStatus` set to `CANCELLED`, it will not be retrieved.
      security:
        - OAuth2:
            - pickpack.pickpack_view
      operationId: GET-pick-pack-retrieve-packlist
      summary: Retrieving a packlist
  '/pick-pack/{tenant}/orders/{orderId}':
    get:
      tags:
        - Orders
      deprecated: true
      description: |-
        Retrieves a specified order's details.
      security:
        - OAuth2:
            - pickpack.pickpack_view
      operationId: GET-pick-pack-retrieve-order
      summary: Retrieving an order
    patch:
      tags:
        - Orders
      deprecated: true
      description: |
        Updates a specified order's status.

        **Note**: If the order has the `packingStatus` set to `CANCELLED`, it is not possible to do any further operations on that order.
      security:
        - OAuth2:
            - pickpack.pickpack_manage
      operationId: PATCH-pick-pack-update-order-status
      summary: Updating an order
  '/pick-pack/{tenant}/orders/{orderId}/assignees':
    post:
      tags:
        - Assignees
      deprecated: true
      description: |
        Adds an assignee to a specified order.

        **Note**: If the order has the `packingStatus` set to `CANCELLED`, it is not possible to modify the assignee for that order.
      security:
        - OAuth2:
            - pickpack.pickpack_manage
      operationId: POST-pick-pack-add-order-assignee
      summary: Adding an assignee to an order
  '/pick-pack/{tenant}/orders/{orderId}/assignees/{assigneeId}':
    delete:
      tags:
        - Assignees
      deprecated: true
      description: |
        Deletes a specified assignee from a specified order.
      security:
        - OAuth2:
            - pickpack.pickpack_manage
      operationId: DELETE-pick-pack-remove-order-assignee
      summary: Deleting an assignee from an order
  '/pick-pack/{tenant}/orders/{orderId}/packaging':
    put:
      tags:
        - Orders
      deprecated: true
      description: |
        Updates packaging products for a specified order.
      security:
        - OAuth2:
            - pickpack.pickpack_manage
      operationId: PUT-pick-pack-update-order-packaging
      summary: Updating packaging products for an order
  '/pick-pack/{tenant}/events':
    post:
      tags:
        - Events
      deprecated: true
      description: |
        Creates a new packing event.

        **Note**: If the order has the `packingStatus` set to `CANCELLED`, it is not possible to create any new packing events for that order.
      security:
        - OAuth2:
            - pickpack.pickpack_manage
      operationId: POST-pick-pack-create-packing-event
      summary: Creating a new packing event
    get:
      tags:
        - Events
      deprecated: true
      description: |-
        Retrieves all events after a specified timestamp.
      security:
        - OAuth2:
            - pickpack.pickpack_view
      operationId: GET-pick-pack-retrieve-packing-event
      summary: Retrieving all events
  '/pick-pack/{tenant}/jobs/recalculations':
    post:
      tags:
        - Recalculations
      deprecated: true
      description: |
        Triggers order recalculation for a specified order list.
      security:
        - OAuth2:
            - pickpack.pickpack_manage
      operationId: POST-pick-pack-start-order-recalculations
      summary: Triggering an order recalculation
  '/pick-pack/{tenant}/jobs/recalculations/{jobId}':
    get:
      tags:
        - Recalculations
      deprecated: true
      description: |
        Retrieves a specified job.
      security:
        - OAuth2:
            - pickpack.pickpack_view
      summary: Retrieving a job
      operationId: GET-pick-pack-retrieve-order-recalculation
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.emporix.io/oauth/token'
          scopes:
            pickpack.pickpack_view: Needed to retrieve information about resources in the service.
            pickpack.pickpack_manage: Needed to manage resources in the service.
security:
  - OAuth2: []
